# Generated by Django 5.2.7 on 2025-10-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
