# Generated by Django 5.2.7 on 2025-10-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_dt_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonusuario',
            name='geracao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
