# Generated by Django 5.2.7 on 2025-10-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pokemonusuario_geracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonusuario',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemonusuario',
            name='base_experiencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemonusuario',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemonusuario',
            name='especie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pokemonusuario',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
