# Generated by Django 5.2.7 on 2025-10-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pokemonusuario_altura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonusuario',
            name='habilidades',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemonusuario',
            name='habitat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pokemonusuario',
            name='stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemonusuario',
            name='tipo_secundario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
